#Депозит денег пользователем
### Создать пользователя
POST http://localhost:4111/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{
  "username": "nkiselchuk",
  "password": "!P327op56",
  "role": "USER"
}
### Залогиниться под пользователем
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
    "username": "nkiselchuk",
    "password": "!P327op56"
}
### Создать счет
POST http://localhost:4111/api/v1/accounts
Authorization: Basic bmtpc2VsY2h1azohUDMyN29wNTY=
Content-Type: application/json

### Депозит денег пользователем (положить денег на счет)
POST http://localhost:4111/api/v1/accounts/deposit
Authorization: Basic bmtpc2VsY2h1azohUDMyN29wNTY=
Content-Type: application/json

{
  "id": 1,
  "balance": 50
}

### Депозит, чтобы баланс стал отрицательным +
### Депозит больше 5000 +
### Депозит ровно 5000 +
### Депозит на ненулевой баланс +
### Депозит на несуществующий счет +
### Депозит на чужой счет (есть 2 пользователя, 1 счет, один переводит на номер счета другого)+


### Перевод себе (у пользователя есть 2 счета, переводит с одного на другой), после перевода проверить баланс на обоих+
### Перевод другому, после перевода проверить баланс на обоих+
### Перевод денег на тот же аккаунт+
### Перевод себе больше чем баланс на счете+
### Перевод другому больше чем баланс на своем счете+
### Перевод отрицательной суммы себе и другому+
### Перевод больше 10000 себе и другому+
### Перевод на несуществующий аккаунт+
### Перевод денег с несуществующего аккаунта+
### Перевод денег с чужого аккаунта



### Авторизованный юзер может изменить имя в профиле (Два слова, состоящее из букв, разделенные пробелом)
### Изменить имя на одно слово
### Изменить имя на несколько слов
### Изменить на пробел
### Изменить на символы
### Изменить на цифры




